examples/EDMD_Examples.jl
examples/SInDy_Examples.jl
src/DataDrivenDiffEq.jl
src/basis.jl
src/sindy.jl
test/runtests.jl

Add ODESystem for basis to resolve #17 .

ODESystem output of SInDy

---

src/sindy.jl

make the simplification not hang

---

Project.toml
examples/SInDy_Examples.jl
src/DataDrivenDiffEq.jl
src/basis.jl
src/extended_dmd.jl
src/optimisers/Optimise.jl
src/optimisers/adm.jl
src/optimisers/admm.jl
src/optimisers/sr3.jl
src/optimisers/strridge.jl
src/sindy.jl
test/runtests.jl

Creates an common interface for sparse regression in SInDy and removes Convex from the table.
Currently implements:
- STRRidge ( From the original SInDy paper)
- Lasso implementation via ADMM
- SR3 implementation
- Alternating Direction Method for Subspace sparsification
Still needs tests in an excluded file and better use of ProximalOperators.jl 
~~Also another LASSO implementation via Coordinate Descent should be included.~~
_Can be done later..._
Relates to #28 and possibly #27

New optimizer structure

---

examples/ISInDy_Examples.jl
src/DataDrivenDiffEq.jl
src/isindy.jl
src/sindy.jl
test/runtests.jl

New [implicit sindy](https://ieeexplore.ieee.org/abstract/document/7809160) implementation using new optimiser interface. 
Is based on #33 and replaces #9 .
Should be merged alongside #33 , but kept as a single PR.

Implicit sindy

---

examples/Basis_Creation.jl

y was not defined so just change it for some fixed parameters

Fix tiny bug in basis creation examples

---

src/sindy.jl
test/runtests.jl

Fixes the segfault in the pareto frontier eval

---

src/sindy.jl
test/runtests.jl

Sindy upgrades

---

src/basis.jl
test/runtests.jl

Minor basis fix

---

Project.toml
examples/SInDy_Examples2.jl
src/DataDrivenDiffEq.jl
src/utils.jl
test/runtests.jl

Add Savitzky Golay filter for numerically estimating differential data from state variables data.

Add basic Savitzky Golay filter

---

examples/Havok_Examples.jl

See https://de5337a9-e467-4569-8f4a-5f1c6678b48f.filesusr.com/ugd/c50953_aadbab271c3641848eef82169f2c78c8.pdf
Add prototype.
Works with the right settings. Still need to get this into an ODE system for simulation.
Tweak SINDy for this.

[WIP] HAVOK

---

src/basis.jl
test/runtests.jl

Adds independent variables to ODESystem creation.
#58

Add independent variable for basis

---

src/DataDrivenDiffEq.jl
src/optimisers/sr3.jl
src/sindy.jl
test/runtests.jl

Return sindy coefficients

---

examples/SInDy_Examples.jl
src/DataDrivenDiffEq.jl
src/optimisers/Optimise.jl
src/optimisers/admm.jl
src/optimisers/sr3.jl
src/optimisers/strridge.jl
src/sindy.jl
test/runtests.jl

Minor sindy updates

---

src/utils.jl

Corrects wrong assertion of bursting; Unified assertions.

Consistent assertion of utils

---

examples/EDMD_Examples.jl
src/extended_dmd.jl

Edmd fixes

---

examples/ISInDy_Examples.jl
examples/SInDy_Examples2.jl

Fix #74 as @AlCap23 suggested.

Fix SInDy_Examples2 and ISInDy_Examples

---

.travis.yml
Project.toml
examples/Basis_Creation.jl
src/basis.jl
src/extended_dmd.jl
src/sindy/isindy.jl
src/sindy/results.jl
src/sindy/sindy.jl
test/basis.jl
test/sindy.jl

Create basis from any function with signature `f(u, p, t)`.
Also adds iip of basis, independent variables and simplifies the structure needed for #73 .

General Basis

---

Project.toml
src/basis.jl
test/koopman.jl
test/optimise.jl

#84 and `DiffEqBase.NullParameters`

Quick fixes

---

src/optimisers/Optimise.jl

Fixed Typo in Optimse

---

README.md

Fixes https://github.com/SciML/DataDrivenDiffEq.jl/issues/99

Update the README to point to the new docs

---

docs/src/sparse_identification/optimisers.md
src/DataDrivenDiffEq.jl
src/optimisers/Optimise.jl
src/optimisers/adm.jl
src/optimisers/pareto.jl
src/sindy/isindy.jl
src/sindy/results.jl
src/sindy/sindy.jl
test/optimise.jl
test/pareto.jl
test/sindy.jl

Implements a better API for pareto methods.
Used for #96 .

Pareto optimiser clean up

---

test/optimise.jl

Since the norm is never zero if we enforce rtol to be higher

Remove norm equality test

---

src/SINDYPI_fit.jl

Just one function fit! takes care of any given ODE.
Tested with 3 examples: (a) Michaelis Menten. (b) Oregonator. (c) Cart Pendulum.
Additonal information about test examples and code results can be found here:
https://rajdandekar.github.io/SINDYPI_Julia/SINDYPIFit/

Added SINDYPI functionality

---

src/basis.jl
src/sindy/results.jl

This fixes things like writing outputs to files.

add io to all prints

---

docs/src/sparse_identification/isindy.md
src/optimizers/pareto.jl
src/sindy/isindy.jl
test/isindy.jl

Fix isindy example in docs and a typo

---

docs/src/sparse_identification/isindy.md
test/isindy.jl

Adapt isindy parameter for documentation

---

docs/src/sparse_identification/isindy.md
examples/ISInDy_Examples.jl
examples/ISInDy_Examples2.jl
src/DataDrivenDiffEq.jl
src/optimizers/Optimize.jl
src/optimizers/adm.jl
src/sindy/isindy.jl
test/isindy.jl

Finally a nice implementation to resolve #82 without further optimizer struggle.

Parallel Implict SINDY

---

src/sindy/isindy.jl
src/sindy/results.jl
test/isindy.jl

Faster equation recovery for explicit result

---

src/optimizers/adm.jl
src/optimizers/admm.jl
src/optimizers/sr3.jl
src/optimizers/strridge.jl
src/sindy/isindy.jl
src/sindy/sindy.jl

This PR adds some missing dots and uses views in some additional places to reduce allocations. 
Some tests for ISINDy failed locally, they appeared to fail due to error being slightly larger than the specified tolerance. I'll leave it for the reviewer to determine whether or not it's my fault or if the tolerance is set too tight :)

Reduce allocations

---

src/basis.jl
src/koopman/extended_dmd.jl

As mentioned in #146 , there are some wrongly stated docs. 
This is a quick and dirty fix by correcting the docs. More information follows in the issue.

Remove wrong documentation for basis creation

---

docs/src/sparse_identification/isindy.md
examples/ISInDy_Examples2.jl
src/sindy/isindy.jl
src/sindy/sindy.jl

Is this sufficient @baggepinnen ? 
The drawback is that the equations of motion can not be generated right now. 
Also, this helps  #109 .

Adapt examples for use with direct inputs

---

docs/src/sparse_identification/isindy.md

Update isindy example in docs

---

docs/src/utils.md
src/DataDrivenDiffEq.jl
src/basis_generators.jl
test/basis.jl

Resolves #153 
Is oriented at the tensor product basis of diffeqflux.

Basis generators

---

docs/make.jl
docs/src/extended_examples.md

Add extended examples for koopman draft

---

src/basis.jl
test/basis.jl

Adapt count operations and introduce linear independent basis

---

src/basis.jl
test/basis.jl

Remove independent variable check on basis creation

---

src/basis.jl

Remove not necessary imports. 
Resolves #190 .

Fixes #190

---

Project.toml
src/DataDrivenDiffEq.jl
src/basis.jl
src/system_conversions.jl

Should fix https://github.com/SciML/DataDrivenDiffEq.jl/issues/193

Update for removal of pins

---

Project.toml
src/basis.jl

Try get the dispatch issue under control for a last release before 0.7

unique! issues

---

docs/src/prob_and_solve.md
docs/src/quickstart.md
src/problem.jl
src/solution.jl
test/dmd/linear_autonomous.jl
test/dmd/linear_forced.jl
test/dmd/nonlinear_autonomous.jl
test/dmd/nonlinear_forced.jl
test/sindy/pendulum.jl

Ode problem dispatch && Printing

---

Project.toml
README.md
src/solution.jl
test/sindy/cartpole.jl

Update lorenz example #219 
Adapt tests #223 
Update julia version
Aaand fixing my stupidity ;)

Minor fixed before release

---

docs/src/prob_and_solve.md
docs/src/quickstart.md
src/DataDrivenDiffEq.jl
src/problem.jl
src/solution.jl
src/solve/koopman.jl
test/dmd/linear_autonomous.jl
test/dmd/linear_forced.jl
test/dmd/nonlinear_autonomous.jl
test/dmd/nonlinear_forced.jl
test/problem.jl
test/sindy/michaelis_menten.jl

#226 
Refines the current problem structure and introduces a `DirectDataDrivenProblem`
ToDo: Dispatch Koopman solve properly, since the inputs do matter

Direct Problem

---

docs/Project.toml
docs/make.jl
docs/src/optimization.md
docs/src/symbolic_regression.md
src/DataDrivenDiffEq.jl
src/symbolic_regression/occamnet.jl

OccamNet Documentation

---

Project.toml
docs/Project.toml
docs/make.jl
docs/src/citations.md
docs/src/prob_and_solve.md
docs/src/symbolic_regression.md
src/DataDrivenDiffEq.jl
src/symbolic_regression/symbolic_regression.jl
test/runtests.jl
test/symbolic_regression/symbolic_regression.jl

@MilesCranmer I linked to SymbolicRegression in the docs. Should I also include the paper for citation or is it fine?

SymbolicRegression API

---

src/solution.jl

Fixes the current situation #293 w.r.t. the symbolic array in the solution

Create array of symbols instead of symbolic array

---

docs/src/examples/nonlinear_systems.md

Solves #292  and replaces #293

Documentation fixes

---

docs/src/getting_started.md
src/solution.jl

Cjm docs quickfix

---

Project.toml

Remove overhead. I (partially) don't know how it got there, but I think not needed.

Remove overhead from Project.toml

---

src/problem/set.jl
src/problem/type.jl
src/utils/collocation.jl
test/problem/problem.jl

Opt-out for the beginning and the end of the collocation data

Ability to crop collocation

---

docs/make.jl
src/basis/type.jl

Had to move `include("pages.jl")` to a point where the docs have been build.

Fix docs build

---

docs/examples/10_noisy_nonlinear.jl
docs/examples/1_linear_discrete_system.jl
docs/examples/2_linear_continuous_system.jl
docs/examples/3_linear_continuous_system_controls.jl
docs/examples/4_nonlinear_continuous_system.jl
docs/examples/5_michaelis_menten.jl
docs/examples/6_autoregulation.jl
docs/examples/7_cartpole.jl
docs/examples/8_symbolic_regression.jl
docs/examples/9_heatequation.jl
src/solution.jl
test/sindy/cartpole.jl
test/sindy/michaelis_menten.jl
test/sindy/pendulum.jl
test/symbolic_regression/occamnet.jl

Solution adaptations

---

README.md
docs/make.jl

I also added the Global Docs badge with the correct link. This just adds more consistency between SciML repos.

updated README and make.jl as per sciml template

---

src/utils/common_options.jl

Adapt Normalisation

---

docs/src/solvers/common.md
lib/DataDrivenDMD/src/result.jl
lib/DataDrivenDMD/src/solve.jl
lib/DataDrivenDMD/test/linear_autonomous.jl
lib/DataDrivenSR/src/DataDrivenSR.jl
lib/DataDrivenSparse/src/solver.jl
src/DataDrivenDiffEq.jl
src/utils/common_options.jl

Make all results selectable by StatsBase interface

Adapt selection
